### ISSUE TITLE
where is "上百种", "换脸", "美颜", "贴纸"?

### ISSUE THREAD

**Issue by lixplor** [Martin20150405/Omoshiroi#1]
做的不错, 不过"上百种", "换脸", "美颜", "贴纸"是什么情况? 只看到有几个滤镜

**Comment by Martin20150405** [comment]
@lixplor 
事情太多了，还没做(* ￣︿￣)
不过确实是这样计划的，两个月之内吧~
不太靠谱的仿msqrd的换脸已经做好了，还没传上去
