### ISSUE TITLE
Add more function please ^^

### ISSUE THREAD

**Issue by ssy06005** [Martin20150405/Omoshiroi#11]
Add more function plz

1. Filter SeekBar
  Want to regulate the filter intensity

![img_2329](https://user-images.githubusercontent.com/22876537/27311223-76abde30-559a-11e7-9466-fffcc01571be.PNG)
[Like This]

2. Gallery picture filter coated
  Not only for live camera, also want used picture 

3. picture size control
  Now we can used only 16:9 , want 4:3  , 1:1

4. Live cam is buffer..TT
  Is my phone is bad?? or if you can fix it??
  
  [FACE_DETECT] activty camera has no buffer
  But
  [MAIN_APP] , [TEST_FACEU] have a buffer

------

and I want donated for you , a little bit..:)
Can you tell me your PayPal account?

Not paying for a favor
I pay tribute to the gratitude of the opensource

I'd appreciate it if you could make a quick update.

and bad english sorry ^^

**Comment by ssy06005** [comment]
@Martin20150405  Please reply :) 👍

**Comment by Martin20150405** [comment]
You can find many similar projects satisfying your needs.
Sorry but I won't add these functions within 6 months.
