### ISSUE TITLE
dependence problem

### ISSUE THREAD

**Issue by YenRen** [Martin20150405/Omoshiroi#13]
Error:Could not download ijkplayer-armv7a.aar (tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.0): No cached version available for offline mode  what's happened? ... was this dependence deleted?

**Comment by Martin20150405** [comment]
I don't think so.
Disable offline mode?

**Comment by YenRen** [comment]
NO, i'm sure is online. now, how to get this dependence.

**Comment by Martin20150405** [comment]
@YenRen 
Don't have a clue. It's the newest version.
Check [here](https://github.com/Bilibili/ijkplayer)

**Comment by YenRen** [comment]
Thanks a lot !
