### ISSUE TITLE
the face filters not apply for the recorded video

### ISSUE THREAD

**Issue by 0x4D3342** [Martin20150405/Omoshiroi#15]
Hi,Martin. Why the face filters not apply for the recorded video? it only work for previewing.

**Comment by Martin20150405** [comment]
I know.

**Comment by 0x4D3342** [comment]
so can you solve it or give me some tips,thanks a lot

**Comment by Martin20150405** [comment]
I will fix it soon.

**Comment by Martin20150405** [comment]
Please check the most recent commit.

**Comment by 0x4D3342** [comment]
It works fine now,thanks a lot
