### ISSUE TITLE
贴纸效果问题

### ISSUE THREAD

**Issue by pananfly** [Martin20150405/Omoshiroi#27]
躺着的时候在录制完去分享到QQ然后回来，贴纸效果不显示，其他时候躺着也偶现无效果（手机型号一加3 android7.1.1）

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Martin20150405** [comment]
商汤的sdk中为了加快检测速度是结合重力感应来判断人脸朝向的。
躺着本来就没效果，可以考虑修改重力传感器的设置。

**Comment by pananfly** [comment]
多谢，最近也有打算研究类似的东西，感谢分享。
